CREATE DATABASE proffurkom CHARACTER SET 'utf8';

CREATE TABLE main_service (
	id INT AUTO_INCREMENT PRIMARY KEY,
	typeService VARCHAR(48),
	descriptionService TEXT(32768)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;